// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['yeelight']['YLightBulb']['Connect']();
}

export function Disconnect() {
  return window['go']['yeelight']['YLightBulb']['Disconnect']();
}

export function GetGuts() {
  return window['go']['yeelight']['YLightBulb']['GetGuts']();
}

export function SelfDiscover() {
  return window['go']['yeelight']['YLightBulb']['SelfDiscover']();
}

export function SendCommand(arg1, arg2) {
  return window['go']['yeelight']['YLightBulb']['SendCommand'](arg1, arg2);
}

export function SetBrightness(arg1) {
  return window['go']['yeelight']['YLightBulb']['SetBrightness'](arg1);
}

export function SetRGB(arg1, arg2, arg3) {
  return window['go']['yeelight']['YLightBulb']['SetRGB'](arg1, arg2, arg3);
}

export function SetRGBInt(arg1) {
  return window['go']['yeelight']['YLightBulb']['SetRGBInt'](arg1);
}

export function SetTemp(arg1) {
  return window['go']['yeelight']['YLightBulb']['SetTemp'](arg1);
}

export function Toggle() {
  return window['go']['yeelight']['YLightBulb']['Toggle']();
}

export function TurnOff() {
  return window['go']['yeelight']['YLightBulb']['TurnOff']();
}

export function TurnOn() {
  return window['go']['yeelight']['YLightBulb']['TurnOn']();
}
