// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['yeelight']['YLightBulb']['Connect']();
}

export function Disconnect() {
  return window['go']['yeelight']['YLightBulb']['Disconnect']();
}

export function SendCommand(arg1, arg2) {
  return window['go']['yeelight']['YLightBulb']['SendCommand'](arg1, arg2);
}

export function Toggle() {
  return window['go']['yeelight']['YLightBulb']['Toggle']();
}

export function TurnOff() {
  return window['go']['yeelight']['YLightBulb']['TurnOff']();
}

export function TurnOn() {
  return window['go']['yeelight']['YLightBulb']['TurnOn']();
}
