// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yeelight} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function SendCommand(arg1:string,arg2:Array<any>):Promise<yeelight.CommandResult>;

export function SetBrightness(arg1:number):Promise<void>;

export function SetRGB(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetRGBInt(arg1:number):Promise<void>;

export function SetTemp(arg1:number):Promise<void>;

export function Toggle():Promise<void>;

export function TurnOff():Promise<void>;

export function TurnOn():Promise<void>;
