// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yeelight} from '../models';

export function Discover():Promise<yeelight.YLightBulb>;

export function Greet(arg1:string):Promise<string>;
