// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2, arg3);
}

export function SetBrightness(arg1, arg2) {
  return window['go']['main']['App']['SetBrightness'](arg1, arg2);
}

export function SetRGB(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRGB'](arg1, arg2, arg3, arg4);
}

export function SetRGBInt(arg1, arg2) {
  return window['go']['main']['App']['SetRGBInt'](arg1, arg2);
}

export function SetTemp(arg1, arg2) {
  return window['go']['main']['App']['SetTemp'](arg1, arg2);
}

export function Toggle(arg1) {
  return window['go']['main']['App']['Toggle'](arg1);
}

export function TurnOff(arg1) {
  return window['go']['main']['App']['TurnOff'](arg1);
}

export function TurnOn(arg1) {
  return window['go']['main']['App']['TurnOn'](arg1);
}
