// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yeelight} from '../models';

export function Connect(arg1:yeelight.YLightBulb):Promise<void>;

export function Disconnect(arg1:yeelight.YLightBulb):Promise<void>;

export function Discover():Promise<yeelight.YLightBulb>;

export function Greet(arg1:string):Promise<string>;

export function SendCommand(arg1:yeelight.YLightBulb,arg2:string,arg3:Array<any>):Promise<yeelight.CommandResult>;

export function SetBrightness(arg1:yeelight.YLightBulb,arg2:number):Promise<void>;

export function SetRGB(arg1:yeelight.YLightBulb,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetRGBInt(arg1:yeelight.YLightBulb,arg2:number):Promise<void>;

export function SetTemp(arg1:yeelight.YLightBulb,arg2:number):Promise<void>;

export function Toggle(arg1:yeelight.YLightBulb):Promise<void>;

export function TurnOff(arg1:yeelight.YLightBulb):Promise<void>;

export function TurnOn(arg1:yeelight.YLightBulb):Promise<void>;
